### PR TITLE
Add git push command for OneSky localization

### PR DESCRIPTION
**Pull request by levieggertcru**

### CODE REVIEW

**Comment by frett** [comment]
I'm a bit undecided on putting this change here. My thoughts:
- I think creating a commit in fastlane is fine, but it should be up to the caller to determine when to push commits to a remote repo.
  - Maybe there's a workflow where you want to manually trigger the download of translations to your local repo, but not push those changes to the remote repo yet.
- I do see that previously there were 2 lanes that pushed to git remote, so we have been doing this in the past with building an adhoc version and bumping the version number.

I'm leaning more towards my first point, which would then be adding a git push step to the GHA job to push up any changes made during a build

**Comment by levieggertcru** [comment]
Hey Daniel, I like the idea of leaving that up to the caller.  Would pushing commits push everything that has been committed during the job?


Wondering if committing the localization file should be optional as well through an argument?

**Comment by frett** [comment]
yeah, pushing from the job could include other changes as well if they are made. so if we wanted to commit the version bump and push that as well.

I'm fine with keeping the commit here and potentially make it optional via a parameter if you want, but the name of the lane does imply it is committed.

For me there is a distinction between making new commits and pushing commits between different repos (local vs remote). making new commits doesn't have any permission restrictions around it, but pushing commits to a remote repo could have restrictions, in theory you could also hae no actual remote repos, or multiple remotes. Those use-cases wouldn't be captured by by a simple push and are better left resolved by the caller

**Comment by frett** [comment]
while talking about this, I believe you need to make the `GITHUB_TOKEN` writable to actually be able to push to the repo. Which also is an argument for keeping the git push in the same place you define permissions to push code.

**Comment by levieggertcru** [comment]
Hey @frett that makes sense to me to keep git push outside of Fastlane.  I will also leave the OneSky lane as is because the naming suggests that those files will be committed.  I'm going to close this PR then.

**Pull request closed without merging**
